[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wali-linux"
version = "0.1.2"
description = "Syscall definitions and ABI for the WebAssembly Linux Interface (WALI)"
readme = "PYPI.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
authors = [{ name = "Arjun Ramesh", email = "arjunr2@andrew.cmu.edu" }]
keywords = ["wasm", "webassembly", "wali", "syscall", "abi", "linux", "spec"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Operating System Kernels :: Linux",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://wasm-thin-kernel-interfaces.github.io/WALI/"
Repository = "https://github.com/Wasm-Thin-Kernel-Interfaces/WALI"

[tool.setuptools.packages.find]
include = ["wali", "wali.*"]

[tool.setuptools.package-data]
wali = ["py.typed"]
